### PR TITLE
Ambray/add pip

### PR DESCRIPTION
**Pull request by louislang**
Implements support for `pip`  in our installation checks. 

## Checklist

- [ ] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [ ] Have you ensured that you have met the expected acceptance criteria?
- [ ] Have you created sufficient tests?
- [ ] Have you updated all affected documentation?

### CODE REVIEW

**Comment by kylewillmon** [comment]
This PR should probably be moved to [phylum-dev/community-extensions](https://github.com/phylum-dev/community-extensions)

**Comment by louislang** [comment]
prob also need to solve the `--dry-run` problem that performs code execution. Or sandbox it, if at all possible.

**Comment by cd-work** [comment]
There's https://github.com/phylum-dev/community-extensions/pull/8 in the community extensions now, is this PR still required?

**Comment by louislang** [comment]
> There's [phylum-dev/community-extensions#8](https://github.com/phylum-dev/community-extensions/pull/8) in the community extensions now, is this PR still required?

I think the extension in the `community-extensions` simply generates a lock file, I _think_ this does the check+install.

**Comment by cd-work** [comment]
Ah right, fair enough. I guess it makes discoverability easier when the `pip` extension doesn't just include the lockfile stuff itself.

**Pull request closed without merging**
