### PR TITLE
Simplify the PR template

### PR DESCRIPTION
**Pull request by kylewillmon**
This patch removes the boilerplate from our pull request template. What
is left is only the checklist, which is important to ensure that nothing
is missed before a PR is merged.

If developers are using detailed commit messages (like this one), PRs
will automatically be created with the detailed commit message followed
by the checklist, which is exactly how we want them.

Fix #321.

## Checklist

- [x] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [x] Have you ensured that you have met the expected acceptance criteria?
- [x] Have you created sufficient tests?
- [x] Have you updated all affected documentation?

### CODE REVIEW

**Review by maxrake — APPROVED** [review]
Works for me. Detailed commit messages are great...and having them automatically populate the PR is even better. Approving, but also mentioning @furi0us333 in case he has some additional SOC2 related insight/background to share.

**Comment by cd-work** [comment]
Is this checklist something motivated by SOC compliance or are there other motivational factors?

I personally feel like pull request templates create a lot of overhead at the wrong place. If you're aware that your PR is missing things, it should likely be created as a draft instead of a finished PR. And the person validating compliance with the acceptance criteria should be a separate party (the reviewer), not the author of the PR?

I understand its motivation as a reminder what kind of things you might want to look at when writing a PR, but that would only be necessary the first or second time. After that I'd assume you know the basic mechanics of the repository. Considering that the majority of contributions in any project come from existing contributors, that seems inefficient.

**Comment by louislang** [comment]
SOC only demands that we track changes in an associated issue tracker. So as long as there is _an issue_ it probably doesn't matter that it's tied to the PR or not. Tying to a PR just helps us down the road should we need to triage something.

**Comment by kylewillmon** [comment]
> SOC only demands that we track changes in an associated issue tracker. So as long as there is _an issue_ it probably doesn't matter that it's tied to the PR or not. Tying to a PR just helps us down the road should we need to triage something.

I am curious about this. Our issue tracker is Github. And Github uses both issues and PRs to track issues. It even uses the same numbering and reference format for PRs and issues (e.g., #321). So for small changes, it seems like the PR itself should be enough to track the issue.

**Review by samtay — APPROVED** [review]

**Pull request merged**
