### PR TITLE
Improve docs for deprecated `phylum history project` commands

### LINKED ISSUE #277: Remove `project` subcommand from `ph history`
# Overview
The `phylum history` command includes a `project` subcommand which feels out of place. We should remove the functionality from this location and users should leverage `phylum project` or `phylum project list` to acquire the same output.

# Expected Behavior
The `phylum history` command does not include a `project` subcommand.

# Additional Context
image

### PR DESCRIPTION
**Pull request by kylewillmon**
This PR deprecates the following ways of calling `phylum history project`:

* Using `phylum history project` to list projects (use `phylum project` instead)
* Using `phylum history project <project_name> <job_id>` to show results for a job (use `phylum history <job_id>` instead)

It also fixes the docs so that they highlight the only remaining useful case, which is using `phylum history project <project_name>` to list jobs for a specific project.

Fixes #277

### CODE REVIEW

**Comment by samtay** [comment]
With these changes, the correct usage of `ph history project` matches well with an optional arg and not a subcommand, i.e., `ph history --project <project-name>`. Perhaps we should make that change in this PR too? For backwards compatibility purposes, we could keep the subcommand but hide it and print deprecation warnings like you've done for the other use cases.

It's worth noting that in its current form:
```
Return information about historical jobs

USAGE:
    phylum history [OPTIONS] [JOB_ID] [SUBCOMMAND]

ARGS:
    <JOB_ID>    The job id to query (or `current` for the most recent job)

OPTIONS:
        --filter <filter>    Provide a filter used to limit the issues displayed

                             EXAMPLES
                             # Show only issues with severity of at least 'high'
                                 --filter=high

                             # Show issues with severity of 'critical' in the 'author'
                             and 'engineering' domains
                                 --filter=crit,aut,eng
    -h, --help               Print help information
    -j, --json               Produce output in json format (default: false)
    -v, --verbose            Increase verbosity of api response.

SUBCOMMANDS:
    help       Print this message or the help of the given subcommand(s)
    project    Show jobs for a specific project

```
the usage is _sort of_ ambiguous, in the sense that you could pass in a `<JOB_ID> == "project"`. Luckily `clap` does handle it pretty smartly.

**Comment by kylewillmon** [comment]
@samtay I completely agree. And, in fact, @cd-work has already been moving forward on implementing this as an optional arg in #290

**Comment by samtay** [comment]
> @samtay I completely agree. And, in fact, @cd-work has already been moving forward on implementing this as an optional arg in #290

Oh whoops, missed that! Great, this looks good to me then.

**Review by samtay — APPROVED** [review]

**Review by maxrake — DISMISSED** [review]

**Comment by kylewillmon** [comment]
This PR is mostly obsolete now that #290 has been merged. But there are still a few documentation updates here that are useful. The docs for `phylum history project` are still available in tab completion:

```
❯ phylum history <TAB><TAB>
help     -- Print this message or the help of the given subcommand(s)
project  -- Show jobs for a specific project (deprecated)
```

And if requested explicitly with `--help` on the hidden subcommand:

```
❯ phylum history project --help
phylum-history-project 
Show jobs for a specific project (deprecated)

USAGE:
    phylum history project [project_name]

ARGS:
    <project_name>    Name of the project

OPTIONS:
    -h, --help    Print help information
```

**Review by maxrake — APPROVED** [review]
LGTM

**Pull request merged**
