### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by jayvdb**
## Checklist

- [ ] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [ ] Have you ensured that you have met the expected acceptance criteria?
- [ ] Have you created sufficient tests?
- [ ] Have you updated all affected documentation?
- [ ] Have you updated CHANGELOG.md (or extensions/CHANGELOG.md), if applicable

### CODE REVIEW

**Review by cd-work — CHANGES_REQUESTED** [review]
Were these changes generated by a tool? If so, I'd be curious which one.

It might make sense to include something that checks for typos in the CI pipeline. Otherwise these types of PRs are going to generate a lot of noise.

**Comment by jayvdb** [comment]
Hiya @cd-work , yes I used https://crates.io/crates/typos-cli , it is very fast.

It is one of the tools at https://github.com/taiki-e/install-action/blob/main/TOOLS.md , so I usually use that to install it into github actions.  I am happy to add that.

**Comment by jayvdb** [comment]
I see this project is using xtask approach.  I could also attempt to add it as an xtask if you would prefer that, using the underlying https://crates.io/crates/typos

**Comment by cd-work** [comment]
You can leave the CI stuff to me. I'll take a look at the options on Monday. I know Winit is using the taiki-e action as a popular Rust project so going with a similar approach might be a good choice.

**Review by cd-work — APPROVED** [review]
LGTM, will handle the CI to automatically spellcheck in a separate PR myself.

**Pull request merged**
